site_name: Knowledge Kindergarten
nav:
    - 首页: index.md
    - 数学基础:
        - 微积分:
            - 数列极限: math/calculus/sequence-limit.md
        - 代数:
            - 集合: math/algebra/set.md
        - 数理逻辑:
            - 符号: math/logic/symbol.md
    - 算法:
        - 散列表/哈希表: algorithm/hash.md
    - 计算机图形学:
        - OpenGL:
            - OpenGL基本概念: graphic/opengl/concept.md
    - 关于我们: about.md
theme: 
    name: material
    language: zh
markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
extra_javascript:
    - javascripts/config.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js